# Generated by Django 5.1.4 on 2025-09-21 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_video', models.FileField(upload_to='banner_video/')),
                ('product1_image', models.ImageField(upload_to='product/')),
                ('product1_video', models.FileField(upload_to='product/')),
                ('product2_image', models.ImageField(upload_to='product/')),
                ('product2_video', models.FileField(upload_to='product/')),
                ('product3_image', models.ImageField(upload_to='product/')),
                ('product3_video', models.FileField(upload_to='product/')),
            ],
        ),
        migrations.CreateModel(
            name='Product_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(upload_to='products/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
    ]
